---
- name: Build SASS
  shell: chdir={{ansistrano_release_path.stdout}}
    SYMFONY_ENV={{symfony_env}} APP_ENV={{symfony_env}} {{symfony_php_path}} {{symfony_console_path}} sass:build {{ symfony_sass_options }}
